name: audio_player
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  audio_manager: any
  percent_indicator: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/be.jpg
    - assets/images/ch.jpg
    - assets/images/des.jpg
    - assets/images/disc.png
    - assets/images/lost.jpg
    - assets/images/our.jpg
    - assets/songs/believer.mp3
    - assets/songs/cherry.mp3
    - assets/songs/dessert.mp3
    - assets/songs/love.mp3
    - assets/songs/stress.mp3
   
