/// Generated by AssetsRefGenerator on 2022/07/30
class Res {
  static const String be = "assets/images/be.jpg";
  static const String believer = "assets/songs/believer.mp3";
  static const String ch = "assets/images/ch.jpg";
  static const String cherry = "assets/songs/cherry.mp3";
  static const String des = "assets/images/des.jpg";
  static const String dessert = "assets/songs/dessert.mp3";
  static const String disc = "assets/images/disc.png";
  static const String lost = "assets/images/lost.jpg";
  static const String love = "assets/songs/love.mp3";
  static const String our = "assets/images/our.jpg";
  static const String stress = "assets/songs/stress.mp3";
}
